version: 0.2
phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - yarn run build
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - dist/**/*
